part of 'userby_user_id_forgot_password_bloc.dart';

@immutable
sealed class UserbyUserIdForgotPasswordState {}

final class UserbyUserIdForgotPasswordInitial extends UserbyUserIdForgotPasswordState {}
class UserbyUserIdForgotPasswordBlocLoading extends UserbyUserIdForgotPasswordState {}
class UserbyUserIdForgotPasswordBlocLoaded extends UserbyUserIdForgotPasswordState {}
class UserbyUserIdForgotPasswordBlocError extends UserbyUserIdForgotPasswordState {}