// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSis51V9JIEA-8dgJ8cUm9Ma3CYDYWUUs',
    appId: '1:811703118064:web:c8cd3510ac1ccf1d8bba35',
    messagingSenderId: '811703118064',
    projectId: 'drive2go-b1be5',
    authDomain: 'drive2go-b1be5.firebaseapp.com',
    storageBucket: 'drive2go-b1be5.appspot.com',
    measurementId: 'G-42X3EGWSPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltoWnK-Ctuta7NjnmSoEDHooiaeEqAtc',
    appId: '1:811703118064:android:e4693b5bdc0e25fc8bba35',
    messagingSenderId: '811703118064',
    projectId: 'drive2go-b1be5',
    storageBucket: 'drive2go-b1be5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAldRkVHlBst2WFclJ8eeOWRDR_0CX4CSs',
    appId: '1:811703118064:ios:99516476f31b61c48bba35',
    messagingSenderId: '811703118064',
    projectId: 'drive2go-b1be5',
    storageBucket: 'drive2go-b1be5.appspot.com',
    iosClientId: '811703118064-a33ujjn7fc9poli974d82f29vq1oja0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.drive2go',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAldRkVHlBst2WFclJ8eeOWRDR_0CX4CSs',
    appId: '1:811703118064:ios:99516476f31b61c48bba35',
    messagingSenderId: '811703118064',
    projectId: 'drive2go-b1be5',
    storageBucket: 'drive2go-b1be5.appspot.com',
    iosClientId: '811703118064-a33ujjn7fc9poli974d82f29vq1oja0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.drive2go',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSis51V9JIEA-8dgJ8cUm9Ma3CYDYWUUs',
    appId: '1:811703118064:web:ea9ba477592dd7648bba35',
    messagingSenderId: '811703118064',
    projectId: 'drive2go-b1be5',
    authDomain: 'drive2go-b1be5.firebaseapp.com',
    storageBucket: 'drive2go-b1be5.appspot.com',
    measurementId: 'G-NF4W9TTNEV',
  );
}
